### ISSUE TITLE
Improve App UI

### ISSUE THREAD

**Issue by Parthav46** [Parthav46/PaytmIntegrationSample#4]
- Change UI elements to better represent data
- Add loader to page to show waiting

**Comment by starboi02** [comment]
Can i work on this?

**Comment by Parthav46** [comment]
For testing you can directly build and run the app. I already have the server side code running on my Firebase project.

**Comment by starboi02** [comment]
Ok thanks! :)

**Comment by starboi02** [comment]
@Parthav46 the app when clicked pay says networkErrror

**Comment by Parthav46** [comment]
Have you replaced Paytm app on your device with Paytm Staging app?
Follow the setup steps given in readme

**Comment by Parthav46** [comment]
@starboi02 
added few review changes for you

**Comment by starboi02** [comment]
@Parthav46 done, please review it.

**Comment by Parthav46** [comment]
@starboi02 one last change

**Comment by starboi02** [comment]
@Parthav46 done .
